AWSAccountID: "729186614334"
AWSProfileRegion: "us-east-1"

App: "aws-cdk-config-example"
Environment: "test"
Version: "0.0.0"
Build: "0"

Parameters:
  LambdaInsightsLayer: "arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:14"
  SomeExternalApiUrl: "https://api-dev.something-external.com"
